### ISSUE TITLE
Remove buttons and subtotal if no items

### ISSUE THREAD

**Issue by UralZima** [techlab/jquery-smartcart#2]
Please add option to remove buttons and subtotal if no items in v3, and show them only when an item is added

**Comment by techlab** [comment]
This would be nice, but I would prefer to disable the buttons than hiding it

**Comment by UralZima** [comment]
It consumes extra space :) On my side, I added style="display: none" on the toolbar and do 'display: block' in _addToCart

**Comment by techlab** [comment]
The v3 release, the checkout and clear buttons will be disabled if the cart has no items.
thank you
