### ISSUE TITLE
Shopping Cart in Top menu.

### ISSUE THREAD

**Issue by sanalrenk** [techlab/jquery-smartcart#5]
Hello, thanks for the nice cart.
this is not issue, I ask question.

How can  I place only this: ![screen shot 2017-05-22 at 11 33 33](https://cloud.githubusercontent.com/assets/21036036/26299275/f388aef2-3ee2-11e7-8bf4-d2413ed72499.png)  in top menu.
Thanks.

**Comment by techlab** [comment]
Well, I don't have an example right now. I will be adding that later.
As a heads-up for you, the below change will make the count to be displayed anywhere on the page.
Add the element where you want to display the count. 
```html
     <span class="sc-cart-count">0</span>
```
Aslo you need to hack one line of source code https://github.com/techlab/SmartCart/blob/master/src/js/jquery.smartCart.js#L357

change from 
```javascript
     $('.sc-cart-count',this.cart_element).text(this.cart.length);
```
to 
```javascript
     $('.sc-cart-count').text(this.cart.length);
```

Hope that helps
Thank you

**Comment by sanalrenk** [comment]
Thanks, it's  working.:)

**Comment by sanalrenk** [comment]
Hello again, it is showing cart items in shopping cart page, but if I go another page, it is reset to zero.
